version: "3.9"
services:
  spark:
    hostname: spark
    stdin_open: true
    tty: true
    container_name: spark
    build:
      context: .
    volumes:
      - ../:/home/PyCon2024/Project
    ports:
      - '8888:8888'
    env_file:
      - 'minio.env'
    entrypoint: /home/PyCon2024/venv/bin/jupyter lab --allow-root --no-browser --ip=0.0.0.0
    networks:
      - lakehouse-network
  trino:
    image: 'trinodb/trino:448'
    hostname: trino
    depends_on:
       - metastore
       - minio
    expose:
      - '8081'
    ports:
      - '8081:8081'
    volumes:
      - ./config/trino:/etc/trino
    networks:
      - lakehouse-network
  postgres:
    image: 'postgres:latest'
    hostname: postgres
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=metastore_db
    ports:
      - '5432:5432'
    networks:
      - lakehouse-network
  metastore:
    image: 'apache/hive:4.0.0'
    hostname: metastore
    depends_on:
      - postgres
    ports:
      - '9083:9083'
    volumes:
      - ./Storage/hive:/opt/hive/data/warehouse
      - type: bind
        source: ./config/hive
        target: /hive_custom_conf
      - type: bind
        source: ./TempPackages/hadoop-aws-3.3.3.jar
        target: /opt/hive/lib/hadoop-aws-3.3.3.jar
      - type: bind
        source: ./TempPackages/aws-java-sdk-bundle-1.11.1026.jar
        target: /opt/hive/lib/aws-java-sdk-bundle-1.11.1026.jar
      - type: bind
        source: ./TempPackages/postgresql-42.7.3.jar
        target: /opt/hive/lib/postgresql-42.7.3.jar
    environment:
      HIVE_CUSTOM_CONF_DIR: /hive_custom_conf
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
    networks:
      - lakehouse-network
  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ../minio-data:/data
    env_file:
      - 'minio.env'
    command: server --console-address ":9001" /data
    networks:
      - lakehouse-network

networks:
  lakehouse-network:
    driver: bridge
